-- V15: "Mua hàng" module - Nhà cung cấp (Supplier) + Nhập hàng (PurchaseOrder)
-- Scope note (see TODO.md for the full write-up): this is the real, working
-- slice of KiotViet's Mua hàng tab - Nhập hàng end to end (create draft, add
-- line items, complete -> increments stock). "Đặt hàng nhập"/"Trả hàng
-- nhập"/"Hóa đơn đầu vào" (siblings in the same KiotViet dropdown) are NOT
-- built - no tables for them here, they stay disabled "Sắp ra mắt" in the UI,
-- same convention as every other unbuilt tab in this app.

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    code character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    phone character varying(30),
    email character varying(200),
    address character varying(500),
    tax_code character varying(50),
    note character varying(1000),
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_suppliers_store_code UNIQUE (store_id, code)
);
ALTER TABLE public.suppliers ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);
ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_suppliers_store ON public.suppliers (store_id);
CREATE INDEX idx_suppliers_name ON public.suppliers (name);

CREATE TABLE public.purchase_orders (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    code character varying(30) NOT NULL,
    supplier_id bigint REFERENCES public.suppliers(id),
    status character varying(20) NOT NULL DEFAULT 'DRAFT',
    total_goods_value numeric(14, 2) NOT NULL DEFAULT 0,
    discount_amount numeric(14, 2) NOT NULL DEFAULT 0,
    amount_paid numeric(14, 2) NOT NULL DEFAULT 0,
    other_costs numeric(14, 2) NOT NULL DEFAULT 0,
    payable_amount numeric(14, 2) NOT NULL DEFAULT 0,
    note character varying(1000),
    created_by_id bigint REFERENCES public.users(id),
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_purchase_orders_store_code UNIQUE (store_id, code)
);
ALTER TABLE public.purchase_orders ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_purchase_orders_store ON public.purchase_orders (store_id);
CREATE INDEX idx_purchase_orders_status ON public.purchase_orders (status);
CREATE INDEX idx_purchase_orders_supplier ON public.purchase_orders (supplier_id);

-- Line items snapshot product_name/product_sku at receipt time (rather than
-- joining live Product) so a completed purchase order stays an accurate
-- historical record even if the product is later renamed - same reasoning
-- as OrderItem's own snapshot fields.
CREATE TABLE public.purchase_order_items (
    id bigint NOT NULL,
    purchase_order_id bigint NOT NULL REFERENCES public.purchase_orders(id),
    product_id bigint NOT NULL REFERENCES public.products(id),
    product_name character varying(200) NOT NULL,
    product_sku character varying(100) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    discount_amount numeric(12, 2) NOT NULL DEFAULT 0,
    line_total numeric(14, 2) NOT NULL DEFAULT 0
);
ALTER TABLE public.purchase_order_items ADD CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_purchase_order_items_order ON public.purchase_order_items (purchase_order_id);
CREATE INDEX idx_purchase_order_items_product ON public.purchase_order_items (product_id);
