-- V19: "Bán hàng" module - the in-store POS sales screen (separate from
-- the online storefront checkout in Order/Payment). A staff member sells
-- directly from the "Bán hàng" terminal: pick products into a cart,
-- optionally attach a walk-in Customer (quick-add, name only required, no
-- login/account - distinct from User), pay with one or several tender
-- types at once (split payment, e.g. part cash + part transfer), and the
-- sale finalizes immediately - no draft/"Phiếu tạm" concept like Nhập hàng,
-- matching the real screen (THANH TOAN completes the sale on the spot).
--
-- Scope note: Order/Payment were NOT reused here even though the shape
-- overlaps - Order requires a registered User and a full shipping address
-- (NotBlank), neither of which exist for a walk-in in-store sale, and
-- Payment is one-to-one with an Order so it cannot represent split tender.
-- Distorting those to fit would mean feeding them fake placeholder data,
-- which this codebase avoids elsewhere (see Supplier/PurchaseOrder's own
-- "not bịa" scope notes). A genuine consequence of keeping them separate:
-- POS sales do NOT yet add into the existing Order-based revenue numbers
-- on "Tổng quan"/Báo cáo - tracked as a follow-up, not done in this slice.

CREATE TABLE public.customers (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    code character varying(30) NOT NULL,
    name character varying(200) NOT NULL,
    phone character varying(30),
    email character varying(200),
    date_of_birth date,
    gender character varying(10),
    address character varying(500),
    region character varying(200),
    ward character varying(200),
    group_name character varying(200),
    note character varying(1000),
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_customers_store_code UNIQUE (store_id, code)
);
ALTER TABLE public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_customers_store ON public.customers (store_id);
CREATE INDEX idx_customers_name ON public.customers (name);

CREATE TABLE public.sales (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    code character varying(30) NOT NULL,
    customer_id bigint REFERENCES public.customers(id),
    subtotal numeric(14, 2) NOT NULL DEFAULT 0,
    discount_amount numeric(14, 2) NOT NULL DEFAULT 0,
    other_collection_amount numeric(14, 2) NOT NULL DEFAULT 0,
    total_amount numeric(14, 2) NOT NULL DEFAULT 0,
    amount_received numeric(14, 2) NOT NULL DEFAULT 0,
    note character varying(1000),
    created_by_id bigint REFERENCES public.users(id),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_sales_store_code UNIQUE (store_id, code)
);
ALTER TABLE public.sales ADD CONSTRAINT sales_pkey PRIMARY KEY (id);
ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_sales_store ON public.sales (store_id);
CREATE INDEX idx_sales_customer ON public.sales (customer_id);

-- Line items snapshot product_name/product_sku at sale time, same reasoning
-- as OrderItem/PurchaseOrderItem's own snapshot fields.
CREATE TABLE public.sale_items (
    id bigint NOT NULL,
    sale_id bigint NOT NULL REFERENCES public.sales(id),
    product_id bigint NOT NULL REFERENCES public.products(id),
    product_name character varying(200) NOT NULL,
    product_sku character varying(100) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    discount_amount numeric(12, 2) NOT NULL DEFAULT 0,
    line_total numeric(14, 2) NOT NULL DEFAULT 0
);
ALTER TABLE public.sale_items ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);
ALTER TABLE public.sale_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_sale_items_sale ON public.sale_items (sale_id);
CREATE INDEX idx_sale_items_product ON public.sale_items (product_id);

-- One row per tender in a (possibly split) payment, e.g. one CASH row and
-- one BANK_TRANSFER row for the same sale - this is the actual "Thanh toán
-- nhiều phương thức" capability, which a singular Payment.paymentMethod
-- column (as used by Order) cannot represent.
CREATE TABLE public.sale_payments (
    id bigint NOT NULL,
    sale_id bigint NOT NULL REFERENCES public.sales(id),
    method character varying(20) NOT NULL,
    amount numeric(14, 2) NOT NULL
);
ALTER TABLE public.sale_payments ADD CONSTRAINT sale_payments_pkey PRIMARY KEY (id);
ALTER TABLE public.sale_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_payments_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_sale_payments_sale ON public.sale_payments (sale_id);
