-- V21: GHN (Giao Hang Nhanh) test shipments - a standalone "create a real
-- sandbox shipment" tool surfaced on the Đối tác giao hàng > Tích hợp >
-- Lịch sử giao hàng tab. Deliberately NOT wired to the storefront Order
-- flow: Order only stores free-text city/state (no GHN district_id/ward_code),
-- and there is no admin order-management screen yet to trigger shipment
-- creation from (Đặt hàng/Hóa đơn are still "Sắp ra mắt"). This table lets
-- the integration be tested end-to-end (create -> webhook/status refresh)
-- without those two much larger prerequisites.

CREATE TABLE public.ghn_shipments (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    created_by_id bigint REFERENCES public.users(id),
    client_order_code character varying(50) NOT NULL,
    ghn_order_code character varying(50),
    to_name character varying(200) NOT NULL,
    to_phone character varying(30) NOT NULL,
    to_address character varying(500) NOT NULL,
    to_province_id integer NOT NULL,
    to_province_name character varying(100) NOT NULL,
    to_district_id integer NOT NULL,
    to_district_name character varying(100) NOT NULL,
    to_ward_code character varying(20) NOT NULL,
    to_ward_name character varying(100) NOT NULL,
    weight_grams integer NOT NULL,
    note character varying(500),
    status character varying(50) NOT NULL,
    shipping_fee numeric(14, 2) NOT NULL DEFAULT 0,
    expected_delivery_time timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_ghn_shipments_client_order_code UNIQUE (client_order_code),
    CONSTRAINT uk_ghn_shipments_ghn_order_code UNIQUE (ghn_order_code)
);
ALTER TABLE public.ghn_shipments ADD CONSTRAINT ghn_shipments_pkey PRIMARY KEY (id);
ALTER TABLE public.ghn_shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ghn_shipments_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_ghn_shipments_store ON public.ghn_shipments (store_id);
CREATE INDEX idx_ghn_shipments_ghn_order_code ON public.ghn_shipments (ghn_order_code);
