-- V25: "Chính sách cửa hàng" - free-named policy entries (đổi trả, vận
-- chuyển, bảo hành, ...) a store owner writes for their own store. Read by
-- the storefront AI chat (see ai/ChatToolExecutor#getStorePolicies) so the
-- assistant answers customers using the store's real policy text instead of
-- guessing. Deliberately no fixed "type" column - same free-naming
-- philosophy as product_attributes, so any industry can define whatever
-- policies matter to them (e.g. "Chính sách đặt bàn" for a restaurant).

CREATE TABLE public.store_policies (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    title character varying(200) NOT NULL,
    content text NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone
);
ALTER TABLE public.store_policies ADD CONSTRAINT store_policies_pkey PRIMARY KEY (id);
ALTER TABLE public.store_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_policies_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_store_policies_store ON public.store_policies (store_id);
