-- V27: POS bank-transfer payment sessions - the missing half of the
-- "Chuyển khoản" QR on the Bán hàng screen.
--
-- That QR used to be display-only (PaymentController#getVietQr): it carried
-- an amount but no transfer content, so when the customer paid, SePay's
-- webhook had nothing to match the incoming transfer against and the app
-- never learned about it - the cashier had to confirm by eye in their own
-- banking app. The storefront never had this problem because an Order
-- exists before the QR does and can lend it a "DH<id>" content; a POS sale
-- is only created at checkout (see V19), so there is nothing to borrow.
--
-- A session is that missing identity, reserved the moment the cashier shows
-- a QR: a unique transfer content ("POS<9 digits>") that the QR embeds, so
-- one single bank account can still tell one counter payment apart from
-- another and from the storefront's own DH<id> orders - no second account
-- and no per-invoice virtual account needed. The webhook flips the row to
-- PAID, and the terminal, polling it, finalizes the sale on its own.
--
-- Deliberately NOT linked to a sale row: the session outlives its screen
-- (a customer can pay a QR the cashier already walked away from) and the
-- sale does not exist yet when the session is created. Reconciliation is
-- by reference + amount + time, which is what the bank statement shows.

CREATE TABLE public.pos_payment_sessions (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    -- Transfer content the customer's bank app carries back to us. Kept
    -- short and alphanumeric on purpose: banking apps commonly truncate
    -- the content field to ~25 chars and some strip punctuation.
    reference character varying(32) NOT NULL,
    amount numeric(14, 2) NOT NULL,
    status character varying(20) NOT NULL,
    -- What actually arrived, which a bank transfer (unlike a gateway call)
    -- can make differ from `amount` - kept for the cashier and for audit.
    transferred_amount numeric(14, 2),
    sepay_transaction_id character varying(64),
    paid_at timestamp(6) without time zone,
    -- Only tells the terminal when to stop polling and ask the cashier to
    -- check manually; a transfer arriving after it is still accepted, since
    -- ignoring real money that reached the account would be worse.
    expires_at timestamp(6) without time zone NOT NULL,
    created_by_id bigint REFERENCES public.users(id),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_pos_payment_sessions_reference UNIQUE (reference)
);
ALTER TABLE public.pos_payment_sessions ADD CONSTRAINT pos_payment_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.pos_payment_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pos_payment_sessions_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_pos_payment_sessions_store ON public.pos_payment_sessions (store_id);
