-- V28: shipping moves from a direct GHN integration to Goship, a carrier
-- aggregator, and the table stops being GHN's.
--
-- The point of the move is that a carrier becomes a per-order choice: one
-- Goship integration prices GHN, GHTK, Viettel Post, J&T, Ninja Van, SPX,
-- BEST and VNPost for the same route at once, and the cashier picks from
-- that list at the counter. A table keyed to one carrier cannot hold that,
-- so carrier_name / carrier_short_name / service / rate_id are columns now.
--
-- This replaces rather than migrates, for two reasons. The address columns
-- change type outright - GHN identifies a province and district with
-- integers, Goship with string codes ("100000", "100300") - so the old
-- values would not fit the new columns even renamed. And every row in
-- ghn_shipments was created against GHN's sandbox by the "Tạo đơn test"
-- form; none of them describe a real delivery worth carrying forward.
--
-- Statuses are Goship's numeric codes (900 = đơn mới, 901 = chờ lấy hàng)
-- kept alongside the Vietnamese label they send with them, rather than
-- mapped to a local enum: the list belongs to Goship and grows without us.

DROP TABLE IF EXISTS public.ghn_shipments;

CREATE TABLE public.shipments (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    created_by_id bigint REFERENCES public.users(id),
    -- Our own reference, sent as Goship's order_id. Booking is asynchronous
    -- there, so a webhook can describe a shipment whose Goship id has not
    -- reached us yet; this handle always exists.
    order_ref character varying(50) NOT NULL,
    goship_id character varying(50),
    tracking_number character varying(50),
    carrier_name character varying(100),
    carrier_short_name character varying(50),
    service character varying(100),
    -- The quote the booking was made against - the only link back to the
    -- price the cashier accepted.
    rate_id character varying(200),
    to_name character varying(200) NOT NULL,
    to_phone character varying(30) NOT NULL,
    to_address character varying(500) NOT NULL,
    -- Text, not integers: Goship's city and district codes are strings and
    -- its ward ids are numbers, and holding both as text means no caller
    -- has to tell them apart.
    to_city_id character varying(20) NOT NULL,
    to_city_name character varying(100) NOT NULL,
    to_district_id character varying(20) NOT NULL,
    to_district_name character varying(100) NOT NULL,
    to_ward_id character varying(20) NOT NULL,
    to_ward_name character varying(100) NOT NULL,
    weight_grams integer NOT NULL,
    length_cm integer,
    width_cm integer,
    height_cm integer,
    cod_amount numeric(14, 2) NOT NULL DEFAULT 0,
    shipping_fee numeric(14, 2) NOT NULL DEFAULT 0,
    status_code integer,
    status_text character varying(100),
    -- "Dự kiến giao 2 ngày" - Goship quotes a phrase, not a date.
    expected character varying(200),
    note character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone
);
ALTER TABLE public.shipments ADD CONSTRAINT shipments_pkey PRIMARY KEY (id);
ALTER TABLE public.shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipments_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_shipments_store ON public.shipments (store_id);
CREATE INDEX idx_shipments_goship_id ON public.shipments (goship_id);
CREATE INDEX idx_shipments_order_ref ON public.shipments (order_ref);
