-- V2: Multi-tenancy foundation (TODO Phase 1.1)
-- stores (tenant root), subscriptions (SaaS billing), users.store_id + users.store_role.
-- Column types mirror what Hibernate maps so ddl-auto=validate passes.

-- ============================== STORES ===============================
CREATE TABLE public.stores (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    logo_url character varying(500),
    phone character varying(20),
    address character varying(255),
    status character varying(20) NOT NULL,
    CONSTRAINT stores_status_check CHECK (status IN ('TRIAL', 'ACTIVE', 'SUSPENDED'))
);

ALTER TABLE public.stores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT uk_stores_slug UNIQUE (slug);

CREATE INDEX idx_store_slug ON public.stores (slug);

-- =========================== SUBSCRIPTIONS ===========================
CREATE TABLE public.subscriptions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    store_id bigint NOT NULL,
    plan character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    paypal_subscription_id character varying(50),
    CONSTRAINT subscriptions_plan_check CHECK (plan IN ('FREE_TRIAL', 'BASIC', 'PRO')),
    CONSTRAINT subscriptions_status_check CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED'))
);

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fk_subscriptions_store FOREIGN KEY (store_id) REFERENCES public.stores(id);

CREATE INDEX idx_subscription_store ON public.subscriptions (store_id);

-- ========================== USERS: TENANT LINK =======================
ALTER TABLE public.users
    ADD COLUMN store_id bigint,
    ADD COLUMN store_role character varying(20);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_store FOREIGN KEY (store_id) REFERENCES public.stores(id);

ALTER TABLE public.users
    ADD CONSTRAINT users_store_role_check CHECK (store_role IN ('OWNER', 'MANAGER', 'STAFF', 'SUPER_ADMIN'));

CREATE INDEX idx_users_store ON public.users (store_id);

-- ============================ DEMO STORE =============================
-- Existing single-store data will be attached to this tenant in the
-- store_id backfill migration (Phase 1.2).
INSERT INTO public.stores (name, slug, status, created_at, updated_at)
VALUES ('Fashion Store Demo', 'fashion-store-demo', 'ACTIVE', now(), now());
