-- V38: "Trả hàng nhập" (PurchaseReturn) - returning goods to the supplier.
-- The sibling V15 deliberately left out, because at that point nothing in the
-- app knew what a return was. KiotViet's supplier detail panel lists PN and
-- THN documents together ("Lịch sử nhập/trả hàng") and nets both into the
-- supplier's công nợ, which is what these tables make possible.
--
-- Mirrors purchase_orders line for line, with the money flowing the other
-- way: refund_amount is what the supplier owes back, amount_received is what
-- they have already handed over. Completing one DECREMENTS stock (the goods
-- leave the shop), where completing a purchase order increments it.
-- Still not built, still "Sắp ra mắt": Đặt hàng nhập and Hóa đơn đầu vào.

CREATE TABLE public.purchase_returns (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    code character varying(30) NOT NULL,
    supplier_id bigint REFERENCES public.suppliers(id),
    status character varying(20) NOT NULL DEFAULT 'DRAFT',
    total_goods_value numeric(14, 2) NOT NULL DEFAULT 0,
    discount_amount numeric(14, 2) NOT NULL DEFAULT 0,
    refund_amount numeric(14, 2) NOT NULL DEFAULT 0,
    amount_received numeric(14, 2) NOT NULL DEFAULT 0,
    note character varying(1000),
    created_by_id bigint REFERENCES public.users(id),
    completed_by_id bigint REFERENCES public.users(id),
    completed_at timestamp(6) without time zone,
    starred boolean NOT NULL DEFAULT false,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_purchase_returns_store_code UNIQUE (store_id, code)
);
ALTER TABLE public.purchase_returns ADD CONSTRAINT purchase_returns_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_returns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_returns_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_purchase_returns_store ON public.purchase_returns (store_id);
CREATE INDEX idx_purchase_returns_status ON public.purchase_returns (status);
CREATE INDEX idx_purchase_returns_supplier ON public.purchase_returns (supplier_id);

-- product_id is nullable and the name/SKU are snapshotted, for the same
-- reason purchase_order_items works that way: deleting a product from the
-- catalog clears the link (AdminProductController#releaseProductReferences)
-- and the paperwork still reads correctly afterwards.
CREATE TABLE public.purchase_return_items (
    id bigint NOT NULL,
    purchase_return_id bigint NOT NULL REFERENCES public.purchase_returns(id),
    product_id bigint REFERENCES public.products(id),
    product_name character varying(200) NOT NULL,
    product_sku character varying(100) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    discount_amount numeric(12, 2) NOT NULL DEFAULT 0,
    line_total numeric(14, 2) NOT NULL DEFAULT 0
);
ALTER TABLE public.purchase_return_items ADD CONSTRAINT purchase_return_items_pkey PRIMARY KEY (id);
ALTER TABLE public.purchase_return_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_return_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_purchase_return_items_return ON public.purchase_return_items (purchase_return_id);
CREATE INDEX idx_purchase_return_items_product ON public.purchase_return_items (product_id);
