-- V39: "Thuế & Kế toán" - tờ khai 01/CNKD for a household business on the
-- kê khai method (Thông tư 40/2021/TT-BTC).
--
-- Only two tables for a whole tax module, and that is the point: a household
-- business is taxed on REVENUE at a fixed percentage, so the return can be
-- computed from invoices the shop already has. Nothing here stores a figure
-- that sales could produce - except the snapshot columns below, which exist
-- precisely so a filed quarter stops moving.
--
-- Periods themselves are not rows either: Quý 3/2026 is arithmetic on the
-- calendar (see TaxPeriod), so a store that opens this screen for the first
-- time sees the right quarters with no seeding job and no backfill.

-- Who the taxpayer is. Apart from Store, which is who the SHOP is: the MST
-- and the registered name belong to the individual who owns the business,
-- and a store that never opens this module carries none of it.
CREATE TABLE public.tax_profiles (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    business_name character varying(200),
    tax_code character varying(20),
    owner_name character varying(200),
    business_address character varying(255),
    tax_office character varying(200),
    tax_method character varying(20) NOT NULL DEFAULT 'KE_KHAI',
    period_type character varying(20) NOT NULL DEFAULT 'QUARTER',
    activity character varying(30) NOT NULL DEFAULT 'DISTRIBUTION',
    exempt_threshold numeric(14, 2) NOT NULL DEFAULT 200000000,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_tax_profiles_store UNIQUE (store_id)
);
ALTER TABLE public.tax_profiles ADD CONSTRAINT tax_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.tax_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tax_profiles_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- What the shop has decided about one period. A row exists only once there
-- IS a decision (filed, or a note typed on it), so an untouched year holds
-- none at all.
--
-- period_type is part of the unique key, not decoration: a shop that moves
-- from quarterly to monthly filing mid-year has both Quý 1 and Tháng 1 of
-- the same year, and they are different returns to different deadlines.
--
-- The four snapshot columns are NULL while a period is unfiled and are
-- written at the moment it is marked nộp. They are what stops a correction
-- made next week from silently restating a quarter the tax office already
-- has - the shop can see its books and its filing disagree, which is the
-- whole reason to keep the copy.
CREATE TABLE public.tax_declarations (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    period_year integer NOT NULL,
    period_type character varying(20) NOT NULL DEFAULT 'QUARTER',
    period_number integer NOT NULL,
    declaration_round integer NOT NULL DEFAULT 1,
    submitted_at timestamp(6) without time zone,
    submitted_by_id bigint REFERENCES public.users(id),
    taxable_revenue numeric(14, 2),
    vat_amount numeric(14, 2),
    pit_amount numeric(14, 2),
    activity character varying(30),
    note character varying(1000),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_tax_declarations_store_period UNIQUE (store_id, period_year, period_type, period_number)
);
ALTER TABLE public.tax_declarations ADD CONSTRAINT tax_declarations_pkey PRIMARY KEY (id);
ALTER TABLE public.tax_declarations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tax_declarations_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_tax_declarations_store ON public.tax_declarations (store_id);

-- Give every existing store the registered name and address it already has
-- on the shop record, so the Thiết lập screen opens part-filled rather than
-- blank. The MST is deliberately left null - guessing one would put a wrong
-- number on a tax return.
INSERT INTO public.tax_profiles (store_id, business_name, business_address, created_at, updated_at)
SELECT s.id, s.name, s.address, NOW(), NOW() FROM public.stores s;
