-- V40: "Trả hàng" (SaleReturn) - goods a customer brings back, against the
-- invoice they bought them on. The customer-facing mirror of V38's "Trả hàng
-- nhập", and the other half of what the Đơn hàng menu has been offering as
-- "Sắp ra mắt".
--
-- Shaped after sales, NOT after purchase_returns, even though the two carry
-- the same word. A return at the counter is atomic the way checkout is: the
-- customer is standing there and the money changes hands on the spot, so
-- there is no "Phiếu tạm" state to move through and therefore no status /
-- completed_by / completed_at columns. created_at IS when it happened.
--
-- sale_id is NOT NULL on purpose. A refund with no invoice behind it is
-- money leaving the till that nothing accounts for; tying every return to an
-- invoice is also what makes "how many of this line may still be returned"
-- answerable at all - see sale_return_items.sale_item_id, summed across every
-- earlier return of the same invoice.
--
-- Deliberately absent: KiotViet's "Đã trả khách / Còn nợ khách" split. That
-- pair only means something with công nợ khách hàng behind it, and a customer
-- here carries no debt balance (see customers, V19/V20) - the shop hands back
-- refund_amount at the counter, or the second number would be a promise
-- nothing in the app ever tracks or collects.

CREATE TABLE public.sale_returns (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    code character varying(30) NOT NULL,
    -- The invoice being returned against, and the customer snapshotted off
    -- it: a walk-in ("khách lẻ") invoice has none, exactly as on sales.
    sale_id bigint NOT NULL REFERENCES public.sales(id),
    customer_id bigint REFERENCES public.customers(id),
    -- "Tổng tiền hàng trả lại" - the returned lines at the prices the invoice
    -- actually charged, never at today's catalog price.
    total_goods_value numeric(14, 2) NOT NULL DEFAULT 0,
    -- "Giảm giá phân bổ" - the returned goods' share of the discounts the
    -- whole invoice got (giảm giá + coupon + điểm). Refunding without it
    -- would hand back money the customer never paid.
    discount_amount numeric(14, 2) NOT NULL DEFAULT 0,
    -- "Phí trả hàng" - what the shop keeps for taking the goods back.
    return_fee numeric(14, 2) NOT NULL DEFAULT 0,
    -- "Cần trả khách" = total_goods_value - discount_amount - return_fee.
    refund_amount numeric(14, 2) NOT NULL DEFAULT 0,
    -- Which till the refund leaves by - the same four tenders a sale is paid
    -- with (sale_payments.method). One method, not a list: a split refund is
    -- not a thing a counter does, where a split payment is.
    refund_method character varying(20) NOT NULL,
    -- "Điểm" put back / taken back. The invoice's redeemed points are
    -- restored in proportion to what came back (the customer spent them on
    -- goods they no longer have), and the points it earned are clawed back
    -- the same way.
    points_restored integer NOT NULL DEFAULT 0,
    points_reverted integer NOT NULL DEFAULT 0,
    note character varying(1000),
    created_by_id bigint REFERENCES public.users(id),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_sale_returns_store_code UNIQUE (store_id, code)
);
ALTER TABLE public.sale_returns ADD CONSTRAINT sale_returns_pkey PRIMARY KEY (id);
ALTER TABLE public.sale_returns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_returns_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_sale_returns_store ON public.sale_returns (store_id);
CREATE INDEX idx_sale_returns_sale ON public.sale_returns (sale_id);
CREATE INDEX idx_sale_returns_customer ON public.sale_returns (customer_id);

-- product_id is nullable and the name/SKU are snapshotted, for the same
-- reason sale_items works that way: deleting a product from the catalog
-- clears the link (AdminProductController#releaseProductReferences) and the
-- paperwork still reads correctly afterwards.
--
-- sale_item_id is NOT NULL and is the one link that is not a snapshot: it is
-- what caps the return at what was actually sold on that line. Sale lines are
-- only ever removed with their invoice, which nothing deletes.
CREATE TABLE public.sale_return_items (
    id bigint NOT NULL,
    sale_return_id bigint NOT NULL REFERENCES public.sale_returns(id),
    sale_item_id bigint NOT NULL REFERENCES public.sale_items(id),
    product_id bigint REFERENCES public.products(id),
    product_name character varying(200) NOT NULL,
    product_sku character varying(100) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    -- This line's share of the discount the invoice line carried, prorated by
    -- how many units came back.
    discount_amount numeric(12, 2) NOT NULL DEFAULT 0,
    line_total numeric(14, 2) NOT NULL DEFAULT 0
);
ALTER TABLE public.sale_return_items ADD CONSTRAINT sale_return_items_pkey PRIMARY KEY (id);
ALTER TABLE public.sale_return_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_return_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
CREATE INDEX idx_sale_return_items_return ON public.sale_return_items (sale_return_id);
CREATE INDEX idx_sale_return_items_sale_item ON public.sale_return_items (sale_item_id);
CREATE INDEX idx_sale_return_items_product ON public.sale_return_items (product_id);
