-- V43: The outbox behind "Tự động hóa" - every automation event the app
-- raises is written here, inside the same transaction as the sale or order
-- that caused it, and a sweeper posts it to n8n afterwards.
--
-- Why a table and not an HTTP call at the point of sale: n8n is a second
-- process, and on a free-tier host a sleeping one takes the best part of a
-- minute to answer its first request. Calling it inline would either block
-- the register on that or drop the notification on the floor. Written here
-- it survives n8n being asleep, down or mid-redeploy, and the same row is
-- the record of what happened to it.
--
-- Why not a Kafka topic: Aiven's free tier caps this project at 5 topics
-- (see KafkaConfig) and Kafka is switchable off entirely on deployments that
-- cannot afford it (spring.kafka.enabled=false). The outbox works either
-- way, and unlike a topic it is something the shop's own screen can show.
--
-- payload is text, not jsonb, on purpose: it is never queried into, only
-- signed and forwarded verbatim, and jsonb rewrites the bytes it is given
-- (key order, whitespace) between the write and the read.

CREATE TABLE public.automation_events (
    id bigint NOT NULL,
    store_id bigint REFERENCES public.stores(id),
    -- Sent as X-Tryum-Delivery. Stable across retries, so a workflow that
    -- already ran can recognise the same delivery arriving twice.
    event_id uuid NOT NULL,
    event_key character varying(60) NOT NULL,
    payload text NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'PENDING',
    attempts integer NOT NULL DEFAULT 0,
    next_attempt_at timestamp(6) without time zone NOT NULL,
    -- When a sweeper took the row. Lets a later sweep reclaim work abandoned
    -- by an instance that died mid-POST, which is the one failure the
    -- SENDING status cannot otherwise recover from.
    claimed_at timestamp(6) without time zone,
    delivered_at timestamp(6) without time zone,
    last_error character varying(500),
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_automation_events_event_id UNIQUE (event_id)
);
ALTER TABLE public.automation_events ADD CONSTRAINT automation_events_pkey PRIMARY KEY (id);
ALTER TABLE public.automation_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.automation_events_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- The sweeper's only query: what is due, oldest first.
CREATE INDEX idx_automation_events_due ON public.automation_events (status, next_attempt_at);
-- The shop's own "lịch sử" read, once the dashboard tab exists.
CREATE INDEX idx_automation_events_store ON public.automation_events (store_id, created_at DESC);
