-- V5: Staff invitations (TODO Phase 2.1)
-- Owner invites staff by email; the invitee creates their account through
-- POST /stores/accept-invite with the emailed token.
-- Column types mirror what Hibernate maps so ddl-auto=validate passes.

CREATE TABLE public.staff_invitations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    store_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    store_role character varying(20) NOT NULL,
    token character varying(64) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    accepted_at timestamp(6) without time zone,
    CONSTRAINT staff_invitations_store_role_check CHECK (store_role IN ('MANAGER', 'STAFF'))
);

ALTER TABLE public.staff_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.staff_invitations
    ADD CONSTRAINT staff_invitations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.staff_invitations
    ADD CONSTRAINT uk_staff_invitations_token UNIQUE (token);

ALTER TABLE ONLY public.staff_invitations
    ADD CONSTRAINT fk_staff_invitations_store FOREIGN KEY (store_id) REFERENCES public.stores(id);

CREATE INDEX idx_staff_invitation_store ON public.staff_invitations (store_id);
CREATE INDEX idx_staff_invitation_email ON public.staff_invitations (email);
