-- n8n keeps its own workflows, credentials and execution history in a
-- database. It is given a schema in this one rather than a container volume,
-- so that the n8n container holds no state at all and can be thrown away,
-- rebuilt or moved to a host with no persistent disk (which is what every
-- free tier is). Flyway owns "public" and never looks in here.
--
-- A safety net rather than a requirement: n8n 2.x creates this schema itself
-- on first boot (verified against 2.40.5 on a pre-existing volume, where this
-- file does not run at all - Postgres only executes it when the data
-- directory is first created). It stays because a future n8n that stops
-- doing that would otherwise fail with a message that says nothing useful.
CREATE SCHEMA IF NOT EXISTS n8n;
